[tox]
requires = tox>=4
envlist =
    # Django alpha
    # py{312,313,314}-djpre

    # Django 5.2
    py{310,311,312,313,314}-dj52,
    # Django 6.x
    py{312,313,314}-dj60,

[virtualenv]
discovery = pyenv

[testenv]
deps =
    pytest-django
    jinja2
    dj52: Django>=5.2,<6.0
    dj60: Django>=6.0,<6.3
    djpre: Django
changedir = tests
commands = pytest {posargs}


# Django pre-release
[testenv:py{312,313,314}-djpre]
pip_pre = True
deps =
    pytest
    pytest-django
    jinja2
    Django
